Add ElectronicParkBreakStatus parameter
smartdevicelink/rpc_spec pull request #102
Opened 2018-06-21 15:16 UTC by conlain-k

fixes #51 

Adds new parameter to match core & hmi changes

2018-09-21 19:49 UTC, jordynmackool approved these changes

2018-10-02 17:43 UTC, theresalech requested changes
This should be targeting `version/4_6_0` branch. @JackLivio can you please fix?

2018-10-02 17:49 UTC, JackLivio commented
@theresalech Updated

2018-10-02 17:59 UTC, theresalech approved these changes

2018-10-02 20:51 UTC, merged