Update PDOP/HDOP/VDOP parameters in api
smartdevicelink/rpc_spec pull request #116
Opened 2018-08-01 21:10 UTC by conlain-k

Fixes #105 by updating XML to match https://github.com/smartdevicelink/sdl_core/pull/2417

2018-09-24 19:34 UTC, theresalech requested changes
@JackLivio can you please review these comments and update accordingly on Conlain's behalf?  One other difference I noticed between this PR and the `Proposed solution` section of the proposal (https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0175-Updating-DOP-value-range-for-GPS-notification.md) is that the proposal shows `dataType` and `resultCode` params within the `VehicleDataResult` struct.  It appears that those have been included in the MOBILE_API.xml since 2.0 (see: https://github.com/smartdevicelink/rpc_spec/blob/67293978702267af00f848d6d1e3f57c824cb94f/MOBILE_API.xml#L1792) so I don't think this is an issue, unless you can identify any other changes needed to that struct.  Let me know of any questions.  Thanks!

2018-09-24 19:34 UTC, theresalech commented on MOBILE_API.xml
> +            <description>PDOP.</description>
Per the proposal, this description should be `PDOP.  If undefined or unavailable, then value shall be set to 0.`

2018-09-24 19:34 UTC, theresalech commented on MOBILE_API.xml
> +            <description>HDOP.</description>
Per the proposal, this description should be `HDOP.  If value is unknown, value shall be set to 0.`

2018-09-24 19:34 UTC, theresalech commented on MOBILE_API.xml
> +            <description>VDOP.</description>
Per the proposal, this description should be `VDOP.  If value is unknown, value shall be set to 0.`

2018-09-27 15:14 UTC, JackLivio commented
@theresalech The VehicleDataResult Struct appears to be a copy and paste error. That field has existed prior to the proposal and wasn't updated

Lines in question:
```
<struct name="VehicleDataResult">
    <description>Individual published data request result</description>
    <param name="dataType" type="VehicleDataType">
      <description>Defined published data element type.</description>
    </param>
    <param name="resultCode" type="VehicleDataResultCode">
      <description>Published data result code.</description>
    </param>
  </struct>
```

2018-09-27 15:24 UTC, Jack-Byrne commented
@theresalech updated based on comments

2018-09-27 15:26 UTC, theresalech approved these changes

2018-09-27 15:43 UTC, JackLivio commented
@theresalech The pdop, hdop, and vdop values do not have a default value listed in the proposal, but the description says that there should be one. I updated the PR to contain default values of 0.

2018-10-01 19:30 UTC, joeygrover approved these changes

2018-10-01 19:31 UTC, merged