Update HD radio parameters
smartdevicelink/rpc_spec pull request #121
Opened 2018-08-21 17:35 UTC by jacobkeeler

Resolves #83

2018-08-21 17:38 UTC, jacobkeeler commented
Note that this is targeting `feature/new_rc_modules_and_parameters`, this will need to be changed before merging

2018-09-24 18:27 UTC, theresalech commented on MOBILE_API.xml
> +            <description> True if the hd radio is on, false is the radio is off</description>
Should this say `false if the radio is off` (instead of `false is the radio is off`)?

2018-09-24 18:31 UTC, theresalech requested changes
@jacobkeeler two questions for your review.  Can you please advise and update accordingly?  Thanks!

2018-09-24 18:31 UTC, theresalech commented on README.md
> +|`hdRadioEnable`|Boolean|False|True if the hd radio is on, false is the radio is off|
Should this say `false if the radio is off` (instead of `false is the radio is off`)?

2018-09-24 18:31 UTC, theresalech commented on MOBILE_API.xml
> +            <description> True if the hd radio is on, false is the radio is off</description>
Should this say false if the radio is off (instead of false is the radio is off)?

2018-09-27 15:32 UTC, jacobkeeler commented
@theresalech comments addressed

2018-09-27 17:20 UTC, theresalech approved these changes

2018-10-02 21:43 UTC, joeygrover approved these changes

2018-10-02 21:43 UTC, merged