Make spaceAvailable non-mandatory
smartdevicelink/rpc_spec pull request #126
Opened 2018-09-04 19:54 UTC by jacobkeeler

Fixes #86

2018-09-06 15:07 UTC, theresalech requested changes
@jacobkeeler it looks like some of the details included in https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0163-make-spaceavailable-field-non-mandatory.md are not reflected in this PR.  See `RPC Spec` section of `Impact on existing code`.

2018-09-06 17:45 UTC, jacobkeeler commented
@theresalech Fixed.

2018-09-17 19:57 UTC, theresalech approved these changes

2018-09-24 15:40 UTC, jordynmackool approved these changes

2018-09-24 19:46 UTC, joeygrover approved these changes

2018-09-24 19:46 UTC, merged