GPS Shift Support
smartdevicelink/rpc_spec pull request #169
Opened 2019-06-07 12:57 UTC by ShobhitAd

Adding `shifted` param to the  `GPSData` struct based on the proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0199-Adding-GPS-Shift-support.md

Note: Targeting master as the base because there are no 5.2 branches yet

2019-06-13 15:22 UTC, theresalech commented
Resolves #128

2019-06-28 15:39 UTC, jacobkeeler requested changes

2019-06-28 15:39 UTC, jacobkeeler commented on MOBILE_API.xml
> +              True, if GPS lat/long, time, and altitude have been purposefully shifted (requires a proprietary algorithm to unshift).
Indent description by 2 more spaces, just for consistency.

2019-06-28 15:49 UTC, jacobkeeler approved these changes

2019-06-28 17:47 UTC, merged

2019-07-16 19:20 UTC, joeygrover reviewed
approved