Implementation: [SDL 0225] Update Published App Services
smartdevicelink/rpc_spec pull request #171
Opened 2019-06-11 19:45 UTC by JackLivio

Update PublishAppService description and add UnpublishAppService RPC.

Fixes #161

2019-07-11 17:15 UTC, jacobkeeler requested changes

2019-07-11 17:15 UTC, jacobkeeler commented on MOBILE_API.xml
> +        <element name="UnpublishAppServiceID" value="56" hexvalue="38" since="5.2" />
```suggestion
        <element name="UnpublishAppServiceID" value="56" hexvalue="38" since="6.0" />
```

2019-07-11 17:15 UTC, jacobkeeler commented on MOBILE_API.xml
> +    <function name="UnpublishAppService" functionID="UnpublishAppServiceID" messagetype="request" since="5.2">
```suggestion
    <function name="UnpublishAppService" functionID="UnpublishAppServiceID" messagetype="request" since="6.0">
```

2019-07-11 17:15 UTC, jacobkeeler commented on MOBILE_API.xml
> +    <function name="UnpublishAppService" functionID="UnpublishAppServiceID" messagetype="response" since="5.2">
```suggestion
    <function name="UnpublishAppService" functionID="UnpublishAppServiceID" messagetype="response" since="6.0">
```

2019-07-19 20:26 UTC, jacobkeeler approved these changes

2019-08-06 18:51 UTC, theresalech requested changes
Should the README.md be updated as well?

2019-09-23 14:28 UTC, theresalech commented
Determined README.md will be updated just before release, and merge conflicts will be resolved just before merge.

2019-09-23 14:29 UTC, theresalech approved these changes

2019-10-14 17:52 UTC, joeygrover approved these changes

2019-10-14 18:02 UTC, merged