Add RPC Message Protection Parameters
smartdevicelink/rpc_spec pull request #191
Opened 2019-08-29 14:39 UTC by JackLivio

Fixes #151

2019-08-29 19:38 UTC, theresalech requested changes
@JackLivio I found one typo in the PR.  Please address, thanks!

2019-08-29 19:38 UTC, theresalech commented on MOBILE_API.xml
> +            <description>SDL receives an un-encrypted PRC request that needs protection. </description>
```suggestion
            <description>SDL receives an un-encrypted RPC request that needs protection. </description>
```

2019-09-24 18:52 UTC, theresalech approved these changes

2019-10-15 18:53 UTC, joeygrover approved these changes

2019-10-15 18:54 UTC, merged