Add reserved keywords
smartdevicelink/rpc_spec pull request #232
Opened 2020-03-23 20:30 UTC by bilal-alsharifi

Fixes #231 

This PR adds a list of keywords that RPC Generators in all platforms (iOS, Java Suite, JavaScript Suite) should avoid using by folowing these rules:
- If the generator needs to create a variable or method and the name was one of the names in the reserved keyword, the generator should append the suffix `param` to it. For example `getFunctionID`  > `getFunctionIDParam`
- Any empty line in the reserved keywords file should be ignored
- Any line in the reserved keywords file that starts with one or more `#` symbols then `space` should be considered a comment and ignored (like `#<space>` or `##<space>` or `###<space>` …)
- Although, the reserved keywords list has a section for each platform, The generator for each platform should avoid using any of the keywords whether it belongs to that platform or another one.

2020-03-24 14:38 UTC, crokita commented
There is a weird case for CancelInteraction where both getFunctionID and setFunctionID are used, but only the getFunctionID is a reserved keyword. If we want consistency with the method name changes, setFunctionID may need to be added to this list so that both will have the same suffix once generated. Thoughts?

2020-03-24 16:04 UTC, bilal-alsharifi commented
Good point @crokita I am okay with adding `setFunctionID` to prevent that weird case from happening. What do you think @joeljfischer ?

2020-03-24 17:15 UTC, joeljfischer commented
> the generator should append the suffix `param` to it. 

For clarity, I think that should be `Param`.

> Any line in the reserved keywords file that starts with one or more # symbols then space should be considered a comment and ignored

I would add that some reserved keywords have a `#` without a `<space>` so it can't just check for `#`

2020-03-24 17:18 UTC, joeljfischer requested changes

2020-03-24 17:18 UTC, joeljfischer commented on RpcParser/RESERVED_KEYWORDS
> +# SDl Java Suite
```suggestion
# Java Suite Library
```

2020-03-24 17:18 UTC, joeljfischer commented on RpcParser/RESERVED_KEYWORDS
> +# SDL JavaScript Suite
```suggestion
# JavaScript Suite Library
```

2020-03-24 17:18 UTC, joeljfischer commented on RpcParser/RESERVED_KEYWORDS
> +# SDL iOS
```suggestion
# iOS Library
```

2020-03-24 17:18 UTC, joeljfischer commented on RpcParser/RESERVED_KEYWORDS
> +## SDL Reserved
```suggestion
# SDL Reserved
```

2020-03-24 17:18 UTC, joeljfischer commented
I think this should also be case insensitive

2020-03-24 17:57 UTC, bilal-alsharifi commented
@joeljfischer I applied your requested changes.

2020-03-24 18:35 UTC, joeljfischer approved these changes

2020-03-24 18:41 UTC, crokita commented
Please resolve my previous question about adding setFunctionID to the list before continuing

2020-03-24 18:46 UTC, bilal-alsharifi commented
@crokita done.

2020-03-25 13:25 UTC, crokita approved these changes

2020-03-25 19:24 UTC, merged