feature/New vehicle data StabilityControlsStatus
smartdevicelink/rpc_spec pull request #233
Opened 2020-03-24 15:33 UTC by SNiukalov

Adds updates to API according to [#200](https://github.com/smartdevicelink/rpc_spec/issues/200)

This PR is **not ready** for review.

### Summary
Adds updates to API of the following RPC:
* GetVehicleData
* SubscribeVehicleData
* UnsubscribeVehicleData
* OnVehicleData

### CLA
* [x]  I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-06-17 07:51 UTC, LitvinenkoIra commented
@atiwari9 please review this PR

2020-06-17 20:30 UTC, atiwari9 commented
PR Approved.

Validated with ATF scripts: [a406f7d](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2421/commits/a406f7d1ca1b1376e1739906b28bb80fc9af2847)


Logs: 
[Test_Results_StabilityControlsStatus_a406f7d_2.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/4794887/Test_Results_StabilityControlsStatus_a406f7d_2.zip)

2020-06-18 07:46 UTC, LitvinenkoIra commented
@theresalech PR is ready for Livio review. Thank you!

2020-07-02 13:07 UTC, ShobhitAd requested changes

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +<interface name="SmartDeviceLink RAPI" version="6.2.0" minVersion="1.0" date="2019-03-19">
The version was bumped up to 7.0. Please merge in the latest changes from develop

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <element name="VEHICLEDATA_STABILITYCONTROLSSTATUS" since="6.2"/>
```suggestion
        <element name="VEHICLEDATA_STABILITYCONTROLSSTATUS" since="7.0"/>
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +    <struct name="StabilityControlsStatus" since="6.2">
```suggestion
    <struct name="StabilityControlsStatus" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="VehicleDataResult" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="VehicleDataResult" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +         <param name="stabilityControlsStatus" type="VehicleDataResult" mandatory="false" since="6.2">
```suggestion
         <param name="stabilityControlsStatus" type="VehicleDataResult" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="StabilityControlsStatus" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="StabilityControlsStatus" mandatory="false" since="7.0">
```

2020-07-02 13:07 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="stabilityControlsStatus" type="StabilityControlsStatus" mandatory="false" since="6.2">
```suggestion
        <param name="stabilityControlsStatus" type="StabilityControlsStatus" mandatory="false" since="7.0">
```

2020-07-09 13:16 UTC, LitvinenkoIra commented
@ShobhitAd thank you for the review, please check the latest updates

2020-07-09 14:03 UTC, ShobhitAd requested changes

2020-07-09 14:03 UTC, ShobhitAd commented on README.md
> +|`stabilityControlsStatus`|StabilityControlsStatus|False|ee StabilityControlsStatus|
```suggestion
|`stabilityControlsStatus`|StabilityControlsStatus|False|See StabilityControlsStatus|
```

2020-07-10 15:40 UTC, ShobhitAd approved these changes

2020-08-05 18:48 UTC, merged