Feature/0266 new vehicle data gear status
smartdevicelink/rpc_spec pull request #252
Opened 2020-05-28 13:18 UTC by mkorniichuk

Implements [#3216](https://github.com/smartdevicelink/sdl_core/issues/3216)

## Summary
Current PR contains an update for `MOBILE_API.xml` and `README.md` introducing new vehicle data type `gearStatus`

2020-06-12 13:26 UTC, IGapchuk commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="1.0" until="6.2"/>
@IGapchuk change to since=2.0

2020-06-12 13:26 UTC, IGapchuk commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="1.0" until="6.2"/>
@IGapchuk change to since 2.0

2020-06-12 13:27 UTC, IGapchuk commented on MOBILE_API.xml
> +                <param name="prndl" type="VehicleDataResult" mandatory="false" since="1.0" until="6.2"/>
@IGapchuk change to since 2.0

2020-06-12 13:27 UTC, IGapchuk commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="1.0" until="6.2"/>
@IGapchuk change to since 2.0 in all related places

2020-06-16 13:01 UTC, LitvinenkoIra commented
@atiwari9 please review this PR

2020-06-17 17:00 UTC, atiwari9 commented
PR Approved.

Validated with atf scripts commit: [b4e023d](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2417/commits/b4e023d4204dc85a3b2889e6fd525512190a8837)

Logs:[Test_Report_Gear_Status_b4e023d_2.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/4793880/Test_Report_Gear_Status_b4e023d_2.zip)

2020-06-18 07:43 UTC, LitvinenkoIra commented
@theresalech PR is ready for Livio review. Thank you!

2020-06-18 15:04 UTC, theresalech commented
@LitvinenkoIra, thanks!  Moving forward, is it possible for Luxoft to reference the issues for the specific repos in the PR description?  For example, this PR resolves issue #217.

2020-06-18 15:29 UTC, LitvinenkoIra commented
@theresalech Yes, I will check all of the PR's and will link them.

2020-07-14 13:42 UTC, ShobhitAd requested changes

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +<interface name="SmartDeviceLink RAPI" version="6.2.0" minVersion="1.0" date="2019-03-19">
Please merge in changes from develop to update the version to 7.0

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <element name="VEHICLEDATA_PRNDL" until="6.2"/>
```suggestion
        <element name="VEHICLEDATA_GEARSTATUS" since="7.0"/>
        <element name="VEHICLEDATA_PRNDL" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <element name="NINTH" since="6.2">
```suggestion
        <element name="NINTH" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <element name="TENTH" since="6.2">
```suggestion
        <element name="TENTH" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +    <enum name="TransmissionType" since="6.2">
```suggestion
    <enum name="TransmissionType" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +    <struct name="GearStatus" since="6.2">
```suggestion
    <struct name="GearStatus" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="VehicleDataResult" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="VehicleDataResult" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="VehicleDataResult" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="VehicleDataResult" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="VehicleDataResult" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="VehicleDataResult" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="VehicleDataResult" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="VehicleDataResult" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="VehicleDataResult" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="VehicleDataResult" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="VehicleDataResult" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="VehicleDataResult" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="Boolean" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="Boolean" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="Boolean" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="Boolean" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="GearStatus" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="GearStatus" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="PRNDL" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="PRNDL" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="PRNDL" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="PRNDL" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="gearStatus" type="GearStatus" mandatory="false" since="6.2">
```suggestion
        <param name="gearStatus" type="GearStatus" mandatory="false" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="prndl" type="PRNDL" mandatory="false" deprecated="true" since="6.2">
```suggestion
        <param name="prndl" type="PRNDL" mandatory="false" deprecated="true" since="7.0">
```

2020-07-14 13:42 UTC, ShobhitAd commented on MOBILE_API.xml
> +                <param name="prndl" type="PRNDL" mandatory="false" since="2.0" until="6.2"/>
```suggestion
                <param name="prndl" type="PRNDL" mandatory="false" since="2.0" until="7.0"/>
```

2020-07-14 13:42 UTC, ShobhitAd commented on README.md
>  |`prndl`|Boolean|False|See PRNDL|
We should add a note in `prndl` stating that the parameter is deprecated
```suggestion
|`prndl`|Boolean|False|See PRNDL. This parameter is deprecated and it is now covered in `gearStatus`|
```
or something similar. Please also add similar notes for the `prndl` param in the other VehicleData RPCs.

2020-07-21 16:26 UTC, LitvinenkoIra commented
@ShobhitAd All comments are processed, please check the latest updates

2020-07-24 17:33 UTC, ShobhitAd approved these changes

2020-08-06 19:30 UTC, merged