[SDL-0296] Possibility to update video streaming capabilities during ignition cycle
smartdevicelink/rpc_spec pull request #272
Opened 2020-07-31 10:39 UTC by LitvinenkoIra

Mobile API updates according to the https://github.com/smartdevicelink/sdl_core/issues/3465

2020-08-18 11:55 UTC, LitvinenkoIra commented
@atiwari9 please review this PR

2020-08-19 20:59 UTC, atiwari9 approved these changes
Approved the PR with below commits:

Test Results:

Logs: 
[2020-08-19_15-57-51.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5099140/2020-08-19_15-57-51.zip)

----------------------------------------------------------------------------------------------------
TOTAL: 44
PASSED: 42 
FAILED: 0 
ABORTED: 0 
SKIPPED: 2 
----------------------------------------------------------------------------------------------------


SDL Core:    [36f2f377929c52f84cb4b4216795fcc5c96f58b4](https://github.com/smartdevicelink/sdl_core/pull/3468/commits/36f2f377929c52f84cb4b4216795fcc5c96f58b4)
RPC Spec:    [4d1312648b78b69f881d97b4b9fd0d8291736750](https://github.com/smartdevicelink/rpc_spec/pull/272/commits/4d1312648b78b69f881d97b4b9fd0d8291736750)
SDL HMI:     [788499f2078e522d710dce3f413045277b278785](https://github.com/smartdevicelink/sdl_hmi/pull/391/commits/788499f2078e522d710dce3f413045277b278785)
Test Scripts: [e6d7f578d52c3b932bc2c5ed9465e9d0c8fd8979](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2437/commits/e6d7f578d52c3b932bc2c5ed9465e9d0c8fd8979)

Please resolve any merge conflicts.

2020-12-18 08:32 UTC, LitvinenkoIra commented
@jordynmackool @JackLivio This PR is ready for Livio review. Thank you!

2021-01-26 02:30 UTC, ShobhitAd requested changes

2021-01-26 02:30 UTC, ShobhitAd commented on MOBILE_API.xml
> +<interface name="SmartDeviceLink RAPI" version="7.1.0" minVersion="1.0" date="2020-11-04">
Please pull the latest changes from develop to update the version to 7.1

2021-01-26 02:30 UTC, ShobhitAd commented on InterfaceParser/parsers/rpc_base.py
> +        """
While python multi-line strings can be used for multi-line comments it might be better here to use the conventional comment style (with `#` at the beginning of each line) to avoid mixing it up with the method docstring.

2021-01-26 02:30 UTC, ShobhitAd commented on InterfaceParser/parsers/rpc_base.py
> +        """
The multi-line string also causes warnings in the code format and quality test `python3 InterfaceParser/test/test_code_format_and_quality.py `
```
...
************* Module parsers.rpc_base
/rpc_spec/InterfaceParser/parsers/rpc_base.py:224:-1: W0105: String statement has no effect (pointless-string-statement)
/rpc_spec/InterfaceParser/parsers/rpc_base.py:248:-1: W0105: String statement has no effect (pointless-string-statement)
...
```

2021-01-26 10:27 UTC, LitvinenkoIra commented on InterfaceParser/parsers/rpc_base.py
> +        """
Done in 8a912616715ae8ff84e4a822ffd87f86ed8bc2da

2021-01-26 10:27 UTC, LitvinenkoIra commented on MOBILE_API.xml
> +<interface name="SmartDeviceLink RAPI" version="7.1.0" minVersion="1.0" date="2020-11-04">
Done in 2695f6d

2021-01-28 14:23 UTC, ShobhitAd commented
@LitvinenkoIra There seem to be some changes from develop in the MOBILE_API.xml file which are being removed/overwritten in this PR (such as the`mediaClock` param being changed in https://github.com/smartdevicelink/rpc_spec/pull/272/files#diff-42ba46e1d01a876881e11902ad4a762c5040d0e7b089b17e7bfaaad9b10cd932R5833 and the countRate param being removed in https://github.com/smartdevicelink/rpc_spec/pull/272/files#diff-42ba46e1d01a876881e11902ad4a762c5040d0e7b089b17e7bfaaad9b10cd932L6040)

Is it possible to revert that commit and try merging in the changes from develop again (or using the develop version and adding in the new video streaming capability parameters again)?

2021-01-28 15:57 UTC, LitvinenkoIra commented
@ShobhitAd Oh I see, sorry for that. I've updated the merge, but I had to force push the branch. Now it should be ok

2021-01-28 16:05 UTC, LitvinenkoIra commented
@ShobhitAd I can see that this PR is still have conflicts, but I'm not sure that the latest commint from the develop branch is correct, could you please check it https://github.com/smartdevicelink/rpc_spec/commit/0110478f9c7ab7f87d526ef194dfa7ef156d2c57 
For example it seems like changes related to the distanceToManeuver https://github.com/smartdevicelink/rpc_spec/commit/0110478f9c7ab7f87d526ef194dfa7ef156d2c57#diff-42ba46e1d01a876881e11902ad4a762c5040d0e7b089b17e7bfaaad9b10cd932R7291 shouldn't be there since they are a part of https://github.com/smartdevicelink/rpc_spec/pull/304

2021-01-28 18:01 UTC, ShobhitAd commented
> @ShobhitAd I can see that this PR is still have conflicts, but I'm not sure that the latest commit from the develop branch is correct, could you please check it [0110478](https://github.com/smartdevicelink/rpc_spec/commit/0110478f9c7ab7f87d526ef194dfa7ef156d2c57)
> For example it seems like changes related to the distanceToManeuver [0110478#diff-42ba46e1d01a876881e11902ad4a762c5040d0e7b089b17e7bfaaad9b10cd932R7291](https://github.com/smartdevicelink/rpc_spec/commit/0110478f9c7ab7f87d526ef194dfa7ef156d2c57#diff-42ba46e1d01a876881e11902ad4a762c5040d0e7b089b17e7bfaaad9b10cd932R7291) shouldn't be there since they are a part of #304

@LitvinenkoIra Merged https://github.com/smartdevicelink/rpc_spec/pull/313 to fix the issue.

2021-01-29 02:37 UTC, ShobhitAd approved these changes

2021-02-12 21:38 UTC, merged