Add C++ keywords to reserved list
smartdevicelink/rpc_spec pull request #288
Opened 2020-10-30 16:10 UTC by joeljfischer

Adds additional keywords to the reserved list to protect for Objective-C++ projects.

2020-11-19 21:36 UTC, bilal-alsharifi approved these changes

2020-11-30 19:00 UTC, renonick87 approved these changes

2020-12-02 19:41 UTC, jacobkeeler requested changes

2020-12-02 19:41 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +inline(1)
```suggestion
inline
```
I don't believe this is part of the actual keyword

2020-12-02 19:41 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +auto(1)
```suggestion
auto
```

2020-12-02 19:43 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +and
```suggestion
and
```

2020-12-02 19:56 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +char
```suggestion
char
char8_t
```
Seems that a few C++20 keywords were omitted, but others were included

2020-12-02 19:56 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +const_cast
```suggestion
consteval
constexpr
constinit
```

2020-12-02 19:57 UTC, jacobkeeler commented on RpcParser/RESERVED_KEYWORDS
> +constexpr
```suggestion
consteval
constexpr
constinit
```

2020-12-03 19:40 UTC, joeljfischer commented
@jacobkeeler This is ready for your review again

2020-12-03 22:24 UTC, jacobkeeler approved these changes

2020-12-04 13:51 UTC, merged