Update RPC Spec for Media Skip Indicators
smartdevicelink/rpc_spec pull request #292
Opened 2020-11-17 15:56 UTC by RHenigan

Fixes #127 
This PR will add the changes needed from the SDL 0198 Proposal for Media Skip Indicators to be able to be set to skip a track at a time or to skip a set amount of time

2020-11-17 15:56 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [SDL 0198] - Media Skip Indicators #871 [0.5]](https://trello.com/c/3Sw6FUMh/515-3-sdl-0198-media-skip-indicators-871-05)

2020-12-15 15:15 UTC, ShobhitAd requested changes
Please merge in the latest changed from develop to change the RAPI version to "7.1.0"

2020-12-15 15:15 UTC, ShobhitAd commented on MOBILE_API.xml
> +        <param name="type" type="SeekIndicatorType" mandatory="true" />
Extra new line between the description and param isn't needed
```suggestion
        </description>
        <param name="type" type="SeekIndicatorType" mandatory="true" />
```

2020-12-16 15:26 UTC, ShobhitAd requested changes

2020-12-16 15:26 UTC, ShobhitAd commented on MOBILE_API.xml
> +                Used to control the forward seek button to either skip back a set amount of time or to the previous track.
```suggestion
                Used to control the back seek button to either skip back a set amount of time or to the previous track.
```

2021-01-11 14:28 UTC, ShobhitAd approved these changes

2021-01-26 21:59 UTC, ShobhitAd commented
@RHenigan Please resolve merge conflicts

2021-01-27 17:27 UTC, merged