[SDL 0238] Feature Keyboard Enhancements
smartdevicelink/rpc_spec pull request #306
Opened 2020-12-18 13:09 UTC by ychernysheva

Implements #183 

This PR is **not ready** for review.

### Summary
Adds new structs and enums to MOBILE API and README corresponding to proposal

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-05 10:19 UTC, KhrystynaDubovyk commented
@ashwink11, please review this PR.

2021-01-06 07:30 UTC, ashwink11 commented
@KhrystynaDubovyk changes approved from the Ford side.

2021-01-08 14:34 UTC, KhrystynaDubovyk commented
@JackLivio This PR is ready for Livio ready. Thank you!

2021-01-08 16:02 UTC, ashwink11 commented
@jordynmackool  this PR is ready for review. Thanks!

2021-01-26 14:32 UTC, jordynmackool commented
@ychernysheva, please update the description of this PR stating that it is "ready for review". Thanks!

2021-02-03 21:34 UTC, jordynmackool commented
@KhrystynaDubovyk the proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [Revise SDL-0238 Keyboard Enhancements](https://github.com/smartdevicelink/sdl_evolution/pull/1119).

Please make the needed updates to this PR and then tag @jacobkeeler to review when ready. Thanks!

2021-02-08 15:50 UTC, ychernysheva commented
@jacobkeeler Revision changes are added, this PR is ready for review. Thank you!

2021-02-08 17:13 UTC, jacobkeeler requested changes

2021-02-08 17:13 UTC, jacobkeeler commented on MOBILE_API.xml
> +        <param name="maskInputCharactersSupported" type="Boolean" mandatory="false" since="7.1" >
```suggestion
        <param name="maskInputCharactersSupported" type="Boolean" mandatory="false">
```
This is implicit due to the `since="7.1"` in the struct definition

2021-02-08 17:13 UTC, jacobkeeler commented on MOBILE_API.xml
> +        </description>
```suggestion
            <description>
                Array of special characters to show in customizable keys.
                If omitted, keyboard will show default special characters
            </description>
```

2021-02-08 17:13 UTC, jacobkeeler commented on MOBILE_API.xml
> +        <param name="customKeys" type="String" maxlength="1" minsize="1" maxsize="10" array="true" mandatory="false"  since="7.1">
```suggestion
        <param name="customKeys" type="String" maxlength="1" minsize="1" maxsize="10" array="true" mandatory="false" since="7.1">
```

2021-02-09 11:29 UTC, ychernysheva commented on MOBILE_API.xml
> +        <param name="maskInputCharactersSupported" type="Boolean" mandatory="false" since="7.1" >
@jacobkeeler Done in c57f5c6

2021-02-09 11:29 UTC, ychernysheva commented on MOBILE_API.xml
> +        </description>
@jacobkeeler Done in c57f5c6

2021-02-09 11:29 UTC, ychernysheva commented on MOBILE_API.xml
> +        <param name="customKeys" type="String" maxlength="1" minsize="1" maxsize="10" array="true" mandatory="false"  since="7.1">
@jacobkeeler Done in c57f5c6

2021-02-09 18:18 UTC, jacobkeeler approved these changes

2021-02-11 22:02 UTC, merged