Add Fuel Range Parameter
smartdevicelink/rpc_spec pull request #88
Opened 2018-05-21 20:07 UTC by JackLivio

[Link to proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md)

2018-05-21 20:26 UTC, theresalech commented
Fixes #34

2018-09-20 19:53 UTC, theresalech requested changes
@JackLivio when comparing to the `Additions to the Mobile_API` section of the proposal, the following seems to be missing from the PR:
>`<param name="fuelRange" type="FuelRange" minsize="0" maxsize="100" array="true" mandatory="false">`

From the proposal, it seems this should be a param in the `UnsubscribeVehicleData` function, but this may have just been an oversight in the proposal.

Can you please take a look and advise?

2018-09-27 15:28 UTC, JackLivio commented
@theresalech That extra line between the UnsubscribeVehicleData response and GetVehicleData request is a typo. It is not in any function and is a copy and paste error.
```
<param name="fuelRange" type="FuelRange" minsize="0" maxsize="100" array="true" mandatory="false">
```

2018-09-27 15:59 UTC, theresalech approved these changes

2018-10-02 18:55 UTC, merged