0037-Expand-Mobile-putfile-RPC
smartdevicelink/rpc_spec pull request #91
Opened 2018-05-23 19:19 UTC by JackLivio

[Link to proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0037-Expand-Mobile-putfile-RPC.md)

2018-05-24 12:46 UTC, theresalech commented
Resolves #40

2018-09-20 20:51 UTC, theresalech requested changes
@JackLivio it looks like there are a few version reference changes required.

2018-09-20 20:51 UTC, theresalech commented on MOBILE_API.xml
> +        <element name="CORRUPTED_DATA" since="4.6">
I think this should be `since="5.0"`

2018-09-20 20:51 UTC, theresalech commented on MOBILE_API.xml
> +        <param name="crc" type="Integer" minvalue="0" maxvalue="4294967295" mandatory="false" since="4.6">
I think this should be `since="5.0"`

2018-09-20 20:51 UTC, theresalech commented on MOBILE_API.xml
> +            <element name=" CORRUPTED_DATA" since="4.6"/>
I think this should be `since="5.0"`

2018-09-27 15:31 UTC, JackLivio commented
@theresalech Updated

2018-09-27 17:12 UTC, theresalech approved these changes

2018-10-02 15:25 UTC, joeygrover approved these changes

2018-10-02 15:25 UTC, merged